# Generated by Django 5.2.1 on 2025-08-17 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for the webhook', max_length=100)),
                ('url', models.URLField(help_text='Target URL for webhook notifications')),
                ('events', models.JSONField(default=list, help_text='List of events this webhook should receive')),
                ('is_active', models.BooleanField(default=True)),
                ('secret_token', models.CharField(blank=True, help_text='Secret token for webhook verification', max_length=255)),
                ('max_retries', models.IntegerField(default=3)),
                ('retry_delay_seconds', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_sent', models.IntegerField(default=0)),
                ('total_failed', models.IntegerField(default=0)),
                ('last_success', models.DateTimeField(blank=True, null=True)),
                ('last_failure', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_webhook_endpoint',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_attempt', models.DateTimeField(blank=True, null=True)),
                ('last_attempt', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='api.webhookendpoint')),
            ],
            options={
                'db_table': 'api_webhook_delivery',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='api_webhook_status_e6be97_idx'), models.Index(fields=['event_type'], name='api_webhook_event_t_d6e6e2_idx'), models.Index(fields=['created_at'], name='api_webhook_created_fd3545_idx')],
            },
        ),
    ]
