# Generated by Django 5.2.1 on 2025-08-17 22:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_add_database_integrity_constraints_fixed'),
        ('vessel_management', '0002_populate_initial_vessel_assignments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transferworkflow',
            name='transfer_workflow_mutual_agreement_logic',
        ),
        migrations.AddConstraint(
            model_name='transferworkflow',
            constraint=models.CheckConstraint(condition=models.Q(('mutual_agreement', False), models.Q(('has_edits', False), ('to_user_confirmed', True)), models.Q(('from_user_confirmed', True), ('has_edits', True), ('to_user_confirmed', True)), _connector='OR'), name='transfer_workflow_mutual_agreement_logic'),
        ),
    ]
