# Generated by Django 5.2.1 on 2025-08-18 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessel_management', '0003_remove_transferworkflow_transfer_workflow_mutual_agreement_logic_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transferworkflow',
            name='completed_by',
            field=models.ForeignKey(blank=True, help_text='User who actually completed/approved the final transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_transfers', to=settings.AUTH_USER_MODEL),
        ),
    ]
