# Generated by Django 5.2.1 on 2025-08-18 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessel_management', '0004_transferworkflow_completed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferworkflow',
            name='from_user',
            field=models.ForeignKey(blank=True, help_text='Final approver from the source vessel (set when transfer confirmed)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiated_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transferworkflow',
            name='to_user',
            field=models.ForeignKey(blank=True, help_text='Final approver from the destination vessel (set when transfer confirmed)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_transfers', to=settings.AUTH_USER_MODEL),
        ),
    ]
