# Generated by Django 5.2.1 on 2025-08-18 19:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_add_database_integrity_constraints_fixed'),
        ('vessel_management', '0005_make_workflow_users_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transferworkflow',
            name='transfer_workflow_different_users',
        ),
        migrations.AddConstraint(
            model_name='transferworkflow',
            constraint=models.CheckConstraint(condition=models.Q(('from_user__isnull', True), ('to_user__isnull', True), models.Q(('from_user', models.F('to_user')), _negated=True), _connector='OR'), name='transfer_workflow_different_users'),
        ),
    ]
