# Generated by Django 5.2.1 on 2025-08-18 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vessel_management', '0006_update_different_users_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transferworkflow',
            name='transfer_workflow_different_users',
        ),
    ]
