# Generated by Django 5.2.1 on 2025-05-31 09:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('vessels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=3, help_text='Cost price per unit when purchased (JOD)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('original_quantity', models.IntegerField(help_text='Original quantity purchased', validators=[django.core.validators.MinValueValidator(1)])),
                ('remaining_quantity', models.IntegerField(help_text='Quantity still available', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_lots', to='products.product')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_lots', to='vessels.vessel')),
            ],
            options={
                'verbose_name': 'Inventory Lot',
                'verbose_name_plural': 'Inventory Lots',
                'ordering': ['vessel', 'product', 'purchase_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('SUPPLY', 'Supply (Stock Received)'), ('SALE', 'Sale (Sold to Customers)'), ('TRANSFER_OUT', 'Transfer Out (Sent to Another Vessel)'), ('TRANSFER_IN', 'Transfer In (Received from Another Vessel)')], max_length=15)),
                ('transaction_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity involved in this transaction', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_price', models.DecimalField(decimal_places=3, help_text='Price per unit for this transaction (JOD)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='products.product')),
                ('related_transfer', models.ForeignKey(blank=True, help_text='Links transfer out with corresponding transfer in', null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
                ('transfer_from_vessel', models.ForeignKey(blank=True, help_text='Source vessel for transfers', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='vessels.vessel')),
                ('transfer_to_vessel', models.ForeignKey(blank=True, help_text='Destination vessel for transfers', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='vessels.vessel')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='vessels.vessel')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
