# Generated by Django 5.2.1 on 2025-05-31 16:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Price per unit for this transaction (JOD)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
    ]
