# Generated by Django 5.2.1 on 2025-06-01 18:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_unit_price'),
        ('vessels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(help_text='Unique purchase order number (e.g., PO001, PO-2025-001)', max_length=50, unique=True)),
                ('po_date', models.DateField(help_text='Date of the purchase order')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this purchase order')),
                ('is_completed', models.BooleanField(default=False, help_text='Whether all items for this PO have been received')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='vessels.vessel')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-po_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='purchase_order',
            field=models.ForeignKey(blank=True, help_text='Purchase order associated with this supply transaction', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supply_transactions', to='transactions.purchaseorder'),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_number', models.CharField(help_text='Unique trip identifier (e.g., TR001, TRIP-2025-001)', max_length=50, unique=True)),
                ('passenger_count', models.IntegerField(help_text='Number of passengers on this trip', validators=[django.core.validators.MinValueValidator(1)])),
                ('trip_date', models.DateField(help_text='Date of the trip')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this trip')),
                ('is_completed', models.BooleanField(default=False, help_text='Whether all sales for this trip have been recorded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='vessels.vessel')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['-trip_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='trip',
            field=models.ForeignKey(blank=True, help_text='Trip associated with this sales transaction', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_transactions', to='transactions.trip'),
        ),
    ]
