# Generated by Django 5.2.1 on 2025-06-11 14:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('transactions', '0003_purchaseorder_transaction_purchase_order_trip_and_more'),
        ('vessels', '0002_vessel_name_ar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VesselProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.DecimalField(decimal_places=3, help_text='Custom selling price for this vessel-product combination (JOD)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='Product with custom pricing (must be general product)', on_delete=django.db.models.deletion.CASCADE, related_name='vessel_prices', to='products.product')),
                ('vessel', models.ForeignKey(help_text='Vessel with custom pricing (must be non-duty-free vessel)', on_delete=django.db.models.deletion.CASCADE, related_name='custom_prices', to='vessels.vessel')),
            ],
            options={
                'verbose_name': 'Vessel Product Price',
                'verbose_name_plural': 'Vessel Product Prices',
                'ordering': ['vessel__name', 'product__item_id'],
                'unique_together': {('vessel', 'product')},
            },
        ),
    ]
