# Generated by Django 5.2.1 on 2025-06-12 06:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('transactions', '0004_vesselproductprice'),
        ('vessels', '0002_vessel_name_ar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['vessel', 'transaction_type', 'transaction_date'], name='transaction_vessel__d9b8e9_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_date', 'vessel'], name='transaction_transac_5c2c61_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['vessel', 'trip_date', 'is_completed'], name='transaction_vessel__eb4041_idx'),
        ),
    ]
