# Generated by Django 5.2.1 on 2025-06-17 10:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_performance_indexes'),
        ('transactions', '0007_vesselproductprice_indexes'),
        ('vessels', '0002_vessel_name_ar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(help_text='Unique purchase order identifier (e.g., PO-AM-001-2024)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or FIFO consumption details'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supply_transactions', to='transactions.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='related_transfer',
            field=models.ForeignKey(blank=True, help_text='Links TRANSFER_OUT with corresponding TRANSFER_IN', null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transfer_from_vessel',
            field=models.ForeignKey(blank=True, help_text='For TRANSFER_IN: source vessel', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='vessels.vessel'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transfer_to_vessel',
            field=models.ForeignKey(blank=True, help_text='For TRANSFER_OUT: destination vessel', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='vessels.vessel'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_transactions', to='transactions.trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_number',
            field=models.CharField(help_text='Unique trip identifier (e.g., AM-001-2024)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vesselproductprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vessel_prices', to='products.product'),
        ),
        migrations.AlterField(
            model_name='vesselproductprice',
            name='selling_price',
            field=models.DecimalField(decimal_places=3, help_text='Custom selling price for this vessel (JOD)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='vesselproductprice',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_prices', to='vessels.vessel'),
        ),
    ]
