# Generated by Django 5.2.1 on 2025-06-22 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_purchaseorder_is_completed_and_more'),
        ('vessels', '0002_vessel_name_ar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='damage_reason',
            field=models.CharField(blank=True, choices=[('DAMAGED', 'Physical Damage'), ('EXPIRED', 'Expired Product'), ('CONTAMINATED', 'Contaminated'), ('RECALL', 'Product Recall'), ('OTHER', 'Other (Specify in Notes)')], help_text='Reason for waste (only for WASTE transactions)', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('SUPPLY', 'Supply (Stock Received)'), ('SALE', 'Sale (Sold to Customers)'), ('TRANSFER_OUT', 'Transfer Out (Sent to Another Vessel)'), ('TRANSFER_IN', 'Transfer In (Received from Another Vessel)'), ('WASTE', 'Waste (Items Removed from Inventory)')], max_length=15),
        ),
        migrations.CreateModel(
            name='WasteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(help_text='Unique waste report identifier (e.g., WR-AM-001-2024)', max_length=50, unique=True)),
                ('report_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_reports', to='vessels.vessel')),
            ],
            options={
                'verbose_name': 'Waste Report',
                'verbose_name_plural': 'Waste Reports',
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='waste_report',
            field=models.ForeignKey(blank=True, help_text='Waste report this transaction belongs to (for WASTE transactions only)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waste_transactions', to='transactions.wastereport'),
        ),
        migrations.AddIndex(
            model_name='wastereport',
            index=models.Index(fields=['vessel'], name='wastereport_vessel_idx'),
        ),
        migrations.AddIndex(
            model_name='wastereport',
            index=models.Index(fields=['report_date'], name='wastereport_date_idx'),
        ),
        migrations.AddIndex(
            model_name='wastereport',
            index=models.Index(fields=['is_completed'], name='wastereport_completed_idx'),
        ),
        migrations.AddIndex(
            model_name='wastereport',
            index=models.Index(fields=['vessel', 'is_completed'], name='wastereport_vessel_status_idx'),
        ),
    ]
