# Generated by Django 5.2.1 on 2025-06-23 20:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_transaction_damage_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylot',
            name='purchase_price',
            field=models.DecimalField(decimal_places=6, help_text='Cost price per unit when purchased (JOD)', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Price per unit for this transaction (JOD)', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
    ]
