# Generated by Django 5.2.1 on 2025-06-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_transfer_model'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_transfer_idx',
        ),
    ]
