# Generated by Django 5.2.1 on 2025-06-29 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_remove_transaction_transaction_transfer_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='boxes',
            field=models.IntegerField(blank=True, help_text='Number of boxes (for supply transactions)', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='transaction',
            name='items_per_box',
            field=models.IntegerField(blank=True, help_text='Items per box (for supply transactions)', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
