# Generated by Django 5.2.1 on 2025-08-11 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_add_fifo_consistency_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryevent',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction'),
        ),
    ]
