# Generated by Django 5.2.1 on 2025-08-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_add_database_integrity_constraints_fixed'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='item_count',
            field=models.PositiveIntegerField(default=0, help_text='Pre-calculated count of items in this PO'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total_cost',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Pre-calculated total cost of all items in this PO', max_digits=12),
        ),
    ]
