# Generated by Django 5.2.1 on 2025-08-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_add_purchaseorder_summary_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='item_count',
            field=models.PositiveIntegerField(default=0, help_text='Pre-calculated count of sales transactions in this trip'),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='item_count',
            field=models.PositiveIntegerField(default=0, help_text='Pre-calculated count of waste transactions in this report'),
        ),
    ]
