# Generated by Django 5.2.1 on 2025-08-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_trip_item_count_wastereport_item_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='total_revenue',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Pre-calculated total revenue from all sales transactions in this trip', max_digits=12),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='total_cost',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Pre-calculated total cost of all waste transactions in this report', max_digits=12),
        ),
    ]
