# Generated by Django 5.2.1 on 2025-08-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_auto_20250821_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='item_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of transfer items (TRANSFER_OUT transactions)'),
        ),
    ]
