# Generated by Django 5.2.1 on 2025-08-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_add_transfer_summary_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='total_cost',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Total cost of all transfer items', max_digits=10),
        ),
    ]
