# Generated by Django 5.2.1 on 2025-06-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='name_ar',
            field=models.CharField(blank=True, help_text='Arabic name of the vessel', max_length=100),
        ),
    ]
