# Generated by Django 5.2.1 on 2025-08-12 06:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0002_vessel_name_ar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vessel',
            index=models.Index(fields=['active'], name='vessel_active_idx'),
        ),
        migrations.AddIndex(
            model_name='vessel',
            index=models.Index(fields=['has_duty_free'], name='vessel_duty_free_idx'),
        ),
        migrations.AddIndex(
            model_name='vessel',
            index=models.Index(fields=['active', 'has_duty_free'], name='vessel_active_duty_free_idx'),
        ),
        migrations.AddConstraint(
            model_name='vessel',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='vessel_name_not_empty'),
        ),
    ]
