"""
Django settings for vessel_sales project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from django.contrib import messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u5_r@=)migd!zt1!8a-1zr8oa3)cs4nxpdp(+9b!e0i!j*)@v@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'vessels',
    'products',
    'transactions',
    'frontend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

USE_I18N = True
USE_L10N = True

ROOT_URLCONF = 'vessel_sales.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vessel_sales.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 6,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Amman'

USE_I18N = True

USE_TZ = True

# Date and Time Formatting
USE_L10N = False  # Enable localization
DATE_FORMAT = 'd/m/Y'  # DD/MM/YYYY format
SHORT_DATE_FORMAT = 'd/m/Y'  # DD/MM/YYYY format
DATETIME_FORMAT = 'd/m/Y H:i'  # DD/MM/YYYY HH:MM format
SHORT_DATETIME_FORMAT = 'd/m/Y H:i'  # DD/MM/YYYY HH:MM format

# Date input formats that Django will accept
DATE_INPUT_FORMATS = [
    '%d/%m/%Y',      # 31/05/2025
    '%d/%m/%y',      # 31/05/25
    '%d-%m-%Y',      # 31-05-2025
    '%d-%m-%y',      # 31-05-25
    '%d.%m.%Y',      # 31.05.2025
    '%d.%m.%y',      # 31.05.25
    '%d/%m%Y',       # 31/052025
    '%d.%m%Y',       # 31.052025
    '%d/%m/%Y',      # 31/5/2025 (single digit month)
    '%d.%m.%Y',      # 31.5.2025 (single digit month)
    '%d-%m-%Y',      # 31-5-2025 (single digit month)
    '%Y-%m-%d',      # 2025-05-31 (ISO format - fallback)
]

DATETIME_INPUT_FORMATS = [
    '%d/%m/%Y %H:%M:%S',     # 25/12/2025 14:30:00
    '%d/%m/%Y %H:%M',        # 25/12/2025 14:30
    '%d-%m-%Y %H:%M:%S',     # 25-12-2025 14:30:00
    '%d-%m-%Y %H:%M',        # 25-12-2025 14:30
    '%Y-%m-%d %H:%M:%S',     # 2025-12-25 14:30:00 (fallback)
    '%Y-%m-%d %H:%M',        # 2025-12-25 14:30 (fallback)
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =============================================================================
# AUTHENTICATION & SECURITY SETTINGS
# =============================================================================

# Authentication Settings
LOGIN_URL = 'frontend:login'
LOGIN_REDIRECT_URL = 'frontend:dashboard'
LOGOUT_REDIRECT_URL = 'frontend/auth/login.html'

# Session Settings
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True

# Security Settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Messages Framework
MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

# User Model (using Django's default)
# If you want custom user model later, add:
# AUTH_USER_MODEL = 'accounts.CustomUser'