# Generated by Django 5.2.1 on 2025-06-23 20:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=6, help_text='Cost price in JOD', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
    ]
