# Generated by Django 5.2.1 on 2025-08-12 06:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_purchase_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='product_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('item_id', ''), _negated=True), name='product_item_id_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_price__gt', 0)), name='product_positive_purchase_price'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('selling_price__gt', 0)), name='product_positive_selling_price'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('selling_price__gte', models.F('purchase_price'))), name='product_selling_price_gte_purchase_price'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('barcode__isnull', True), models.Q(('barcode', ''), _negated=True), _connector='OR'), name='product_barcode_not_empty_string'),
        ),
    ]
